# Generated by Django 3.2.18 on 2023-05-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('classifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='supporters',
            field=models.ManyToManyField(blank=True, to='users.Member', verbose_name='supporters'),
        ),
    ]
