# Generated by Django 3.2.18 on 2023-04-09 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='groups/%Y/%m/%d/', verbose_name='photo')),
                ('about', models.TextField(blank=True, default='', verbose_name='about')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='users.member', verbose_name='creator')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='member')),
                ('small_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_groups.smallgroup', verbose_name='small group')),
            ],
            options={
                'verbose_name': 'group member',
                'verbose_name_plural': 'group members',
            },
        ),
    ]
