# Generated by Django 3.2.18 on 2023-05-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'group member',
                'verbose_name_plural': 'group members',
            },
        ),
        migrations.CreateModel(
            name='SmallGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='groups/%Y/%m/%d/', verbose_name='photo')),
                ('about', models.TextField(blank=True, default='', verbose_name='about')),
                ('enabled', models.BooleanField(blank=True, default=True, verbose_name='enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cause', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='classifications.cause', verbose_name='cause')),
            ],
            options={
                'verbose_name': 'small group',
                'verbose_name_plural': 'small groups',
            },
        ),
    ]
