# Generated by Django 3.2.18 on 2023-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('small_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smallgroup',
            options={'verbose_name': 'small group', 'verbose_name_plural': 'small groups'},
        ),
        migrations.AddField(
            model_name='smallgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='small_groups', through='small_groups.GroupMember', to='users.Member'),
        ),
    ]
