# Generated by Django 3.2.18 on 2023-05-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('small_groups', '0001_initial'),
        ('classifications', '0002_cause_supporters'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallgroup',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.member', verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='smallgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='small_groups', through='small_groups.GroupMember', to='users.Member'),
        ),
        migrations.AddField(
            model_name='smallgroup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='groups', to='classifications.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='small_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_groups.smallgroup', verbose_name='small group'),
        ),
    ]
