# Generated by Django 3.2.18 on 2023-05-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallgroup',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='smallgroup',
            name='tags',
        ),
    ]
