# Generated by Django 3.2.18 on 2023-04-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('small_groups', '0002_auto_20230409_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallgroup',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.member', verbose_name='creator'),
        ),
    ]
