# Generated by Django 3.2.18 on 2023-05-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230525_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_church_leader',
        ),
        migrations.AddField(
            model_name='member',
            name='orientation',
            field=models.CharField(blank=True, choices=[('Bisexual', 'Bisexual'), ('Gay', 'Gay'), ('Heterosexual', 'Heterosexual'), ('Lesbian', 'Lesbian'), ('Pansexual', 'Pansexual'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=75, verbose_name='orientation'),
        ),
        migrations.AddField(
            model_name='member',
            name='political_ideology',
            field=models.CharField(blank=True, choices=[('Anarchism', 'Anarchism'), ('Communism', 'Communism'), ('Conservatism', 'Conservatism'), ('Democracy', 'Democracy'), ('Environmentalism', 'Environmentalism'), ('Liberalism', 'Liberalism'), ('Libertarianism', 'Libertarianism'), ('Nationalism', 'Nationalism'), ('Non-political', 'Non-political'), ('Populism', 'Populism'), ('Progressivism', 'Progressivism'), ('Social Democracy', 'Social Democracy'), ('Socialism', 'Socialism'), ('Transhumanism', 'Transhumanism'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=75, verbose_name='political ideology'),
        ),
        migrations.AddField(
            model_name='member',
            name='religion',
            field=models.CharField(blank=True, choices=[('Bahai Faith', 'Bahai Faith'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Druze', 'Druze'), ('Traditional Religion', 'Traditional Religion'), ('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Jainism', 'Jainism'), ('Judaism', 'Judaism'), ('None', 'None'), ('Paganism', 'Paganism'), ('Sikhism', 'Sikhism'), ('Scientology', 'Scientology'), ('Shinto', 'Shinto'), ('Spiritism', 'Spiritism'), ('Spiritual', 'Spiritual (but not listed)'), ('Taoism', 'Taoism'), ('Unaffiliated', 'Unaffiliated'), ('Vodou', 'Vodou'), ('Zoroastrianism', 'Zoroastrianism'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=75, verbose_name='religion'),
        ),
    ]
