# Generated by Django 3.2.18 on 2023-06-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230527_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='religion',
        ),
        migrations.AddField(
            model_name='member',
            name='denomination',
            field=models.CharField(blank=True, choices=[('Catholic', (('Latin Church', 'Latin Church'), ('Alexandrian Rite', 'Alexandrian Rite'), ('Armenian Rite', 'Armenian Rite'), ('Byzantine Rite', 'Byzantine Rite'), ('East Syriac Rite', 'East Syriac Rite'), ('West Syriac Rite', 'West Syriac Rite'))), ('Eastern Orthodox', (('Greek Orthodox', 'Greek Orthodox'), ('Albanian Orthodox', 'Albanian Orthodox'), ('Vicariate for Palestine and Jordan', 'Vicariate for Palestine and Jordan'), ('Finnish Orthodox', 'Finnish Orthodox'), ('Korean Orthodox', 'Korean Orthodox'), ('Estonian Orthodox', 'Estonian Orthodox'), ('Ukrainian Orthodox', 'Ukrainian Orthodox'), ('Orthodox Metropolitanate of Singapore', 'Orthodox Metropolitanate of Singapore'), ('American Carpatho-Russian Orthodox', 'American Carpatho-Russian Orthodox'), ('Antiochian Orthodox', 'Antiochian Orthodox'), ('Russian Orthodox', 'Russian Orthodox'), ('Japanese Orthodox', 'Japanese Orthodox'), ('Chinese Orthodox', 'Chinese Orthodox'), ('Moldovan Orthodox', 'Moldovan Orthodox'), ('Belarusian Orthodox', 'Belarusian Orthodox'), ('Philippine Orthodox', 'Philippine Orthodox'), ('Georgian Orthodox', 'Georgian Orthodox'), ('Serbian Orthodox', 'Serbian Orthodox'), ('Romanian Orthodox', 'Romanian Orthodox'), ('Bulgarian Orthodox', 'Bulgarian Orthodox'), ('Cypriot Orthodox', 'Cypriot Orthodox'), ('Orthodox Church of Greece', 'Orthodox Church of Greece'), ('Polish Orthodox', 'Polish Orthodox'), ('Orthodox Church in America', 'Orthodox Church in America'), ('Orthodox Church of Ukraine', 'Orthodox Church of Ukraine'), ('Macedonian Orthodox', 'Macedonian Orthodox'))), ('Oriental Orthodox', (('Armenian Apostolic', 'Armenian Apostolic'), ('Coptic Orthodox', 'Coptic Orthodox'), ('Eritrean Orthodox Tewahedo', 'Eritrean Orthodox Tewahedo'), ('Ethiopian Orthodox Tewahedo', 'Ethiopian Orthodox Tewahedo'), ('Malankara Orthodox Syrian', 'Malankara Orthodox Syrian'), ('Syriac Orthodox', 'Syriac Orthodox'))), ('Nontrinitarian', (('Unitarian Universalist', 'Unitarian Universalist'), ('Unitarian', 'Unitarian'), ('Latter Day Saints', 'Latter Day Saints'), ('Jahovah Witness', 'Jahovah Witness'), ('Swedenborgianism', 'Swedenborgianism'), ('Christian Science', 'Christian Science'))), ('Protestant', (('Lutheran', 'Lutheran'), ('Reformed', 'Reformed'), ('Anglican', 'Anglican'), ('Anabaptist', 'Anabaptist'), ('Baptist', 'Baptist'), ('Methodist', 'Methodist'), ('Adventist', 'Adventist'), ('Quaker', 'Quaker'), ('Plymouth Brethren', 'Plymouth Brethren'), ('Pentecostal', 'Pentecostal'), ('Charismatic', 'Charismatic'), ('Presbyterian', 'Presbyterian'), ('Evangelical', 'Evangelical'), ('Eastern Protestant', 'Eastern Protestant'), ('Messianic Judaism', 'Messianic Judaism'))), ('None', (('Theist', 'Theist'), ('Agnositic', 'Agnositic'), ('Atheist', 'Atheist')))], default='Theist', max_length=75, verbose_name='denomination'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=14, null=True, verbose_name='gender'),
        ),
    ]
