# Generated by Django 3.2.18 on 2023-04-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='people_needed',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='people needed'),
        ),
    ]
