# Generated by Django 3.2.18 on 2023-05-24 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='beneficiaries',
        ),
        migrations.RemoveField(
            model_name='project',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vision',
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(blank=True, verbose_name='problem')),
                ('goal', models.TextField(blank=True, verbose_name='goal')),
                ('beneficiaries', models.TextField(blank=True, verbose_name='beneficiaries')),
                ('importance', models.TextField(blank=True, verbose_name='importance')),
                ('solution', models.TextField(blank=True, verbose_name='solution')),
                ('execution', models.TextField(blank=True, verbose_name='execution')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'action plan',
                'verbose_name_plural': 'action plans',
            },
        ),
    ]
