# Generated by Django 3.2.18 on 2023-06-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20230524_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'proposal', 'verbose_name_plural': 'proposals'},
        ),
        migrations.AlterField(
            model_name='proposal',
            name='beneficiaries',
            field=models.TextField(blank=True, default='', verbose_name='beneficiaries'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='execution',
            field=models.TextField(blank=True, default='', verbose_name='execution'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='goal',
            field=models.TextField(blank=True, default='', verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='importance',
            field=models.TextField(blank=True, default='', verbose_name='importance'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='problem',
            field=models.TextField(blank=True, default='', verbose_name='problem'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='solution',
            field=models.TextField(blank=True, default='', verbose_name='solution'),
        ),
    ]
