# Generated by Django 3.2.18 on 2023-05-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_body',
        ),
    ]
