# Generated by Django 3.2.18 on 2023-04-07 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundraisers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='users.member', verbose_name='donor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='fundraiser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='fundraisers.fundraiser', verbose_name='fundraiser'),
        ),
    ]
