# Generated by Django 3.2.18 on 2023-03-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name')),
                ('overview', models.TextField(blank=True, default='', verbose_name='overview')),
                ('vision', models.TextField(blank=True, default='', verbose_name='vision')),
                ('beneficiaries', models.JSONField(blank=True, default=list, null=True, verbose_name='beneficiaries')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('financial_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='financial goal')),
                ('funds_raised', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='funds raised')),
                ('published', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cause',
                'verbose_name_plural': 'causes',
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Staff', 'Staff'), ('Supporter', 'Supporter'), ('Donor', 'Donor')], default='Supporter', max_length=10, verbose_name='role')),
                ('position', models.CharField(blank=True, max_length=128, verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'campaign member',
                'verbose_name_plural': 'campaign members',
            },
        ),
    ]
