# Generated by Django 3.2.18 on 2023-03-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmember',
            name='member',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cause',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.cause', verbose_name='cause'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_managed', to='users.member', verbose_name='manager'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='campaigns', through='campaigns.CampaignMember', to='users.Member'),
        ),
    ]
