# Generated by Django 3.2.18 on 2023-03-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('open', models.BooleanField(default=True, verbose_name='open')),
                ('people_needed', models.PositiveIntegerField(blank=True, default=1, verbose_name='people_needed')),
                ('positions_filled', models.PositiveIntegerField(blank=True, default=0, verbose_name='positions filled')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='campaigns.campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('results', models.TextField(blank=True, null=True, verbose_name='results')),
                ('start_date', models.DateField(null=True, verbose_name='start date')),
                ('deadline', models.DateField(null=True, verbose_name='deadline')),
                ('complete_date', models.DateField(null=True, verbose_name='complete date')),
                ('complete', models.BooleanField(blank=True, default=False, verbose_name='complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='campaigns.campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'goal',
                'verbose_name_plural': 'goals',
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('item', models.CharField(blank=True, max_length=128, verbose_name='item')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='purpose')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='campaigns.campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'expenditure',
                'verbose_name_plural': 'expenditures',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(blank=True, default=False, verbose_name='selected')),
                ('qualifications', models.TextField(blank=True, null=True, verbose_name='qualifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.member', verbose_name='member')),
                ('position', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='campaigns.position', verbose_name='position')),
            ],
            options={
                'verbose_name': 'applicant',
                'verbose_name_plural': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('label', models.CharField(blank=True, max_length=128, verbose_name='label')),
                ('task', models.TextField(blank=True, null=True, verbose_name='task')),
                ('results', models.TextField(blank=True, null=True, verbose_name='results')),
                ('start_date', models.DateField(null=True, verbose_name='start date')),
                ('deadline', models.DateField(null=True, verbose_name='deadline')),
                ('complete_date', models.DateField(null=True, verbose_name='complete date')),
                ('complete', models.BooleanField(blank=True, default=False, verbose_name='complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='campaigns.goal', verbose_name='goal')),
            ],
            options={
                'verbose_name': 'action',
                'verbose_name_plural': 'actions',
            },
        ),
    ]
