# Generated by Django 3.2.18 on 2023-03-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20230327_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='complete_date',
            field=models.DateField(blank=True, null=True, verbose_name='complete date'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
